version: 2
workflows:
  version: 2
  build:
    jobs:
      - node-base
      - node-8
      - node-10

jobs:
  node-base: &build-and-test
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Build the lib
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Wait for redis to become available"
          command: |
            dockerize -wait tcp://127.0.0.1:6379 -timeout 120s
            while ! mysqladmin ping -h 127.0.0.1:6379 --silent; do
              echo "Waiting for redis to become available"
              sleep 1
            done

      # Lint + Test
      - run: npm run test

  node-6:
    <<: *build-and-test
    docker:
      - image: circleci/node:6

  node-8:
    <<: *build-and-test
    docker:
      - image: circleci/node:8

  node-10:
    <<: *build-and-test
    docker:
      - image: circleci/node:10
