#!/bin/sh
printf "\nYou're about to push to a remote repository, running tests first:\n"

npm test
exit_code=$?

if [ ! 0 = "$exit_code" ]
then
    printf "\033[0;31m \nPush aborted, some tests are failing, please fix them before pushing...\033[0m \n"
fi

exit $exit_code
