---
name: CI

on:
  pull_request:
  push:
    branches:
      - trunk
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Setup and install
        uses: Automattic/vip-actions/nodejs-setup@trunk
        with:
          node-version-file: .nvmrc

      - name: Run linter
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

  jest:
    name: Run unit tests
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Setup and install
        uses: Automattic/vip-actions/nodejs-setup@trunk
        with:
          node-version-file: .nvmrc

      - name: Run tests
        run: npm run jest
